<?php
/**
 * Admin notification email template.
 *
 * @var array $context
 */

declare( strict_types=1 );

if ( ! defined( 'ABSPATH' ) ) {
exit;
}

$branding = $context['branding'] ?? [];
$job_title = $context['job_title'] ?? '';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title><?php esc_html_e( 'New Application Received', 'widezone-core' ); ?></title>
<style>
body { font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background: #f4f4f7; color: #002b5b; margin: 0; padding: 2rem; }
.container { max-width: 640px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 24px 60px -32px rgba(0, 43, 91, 0.35); }
.header { padding: 1.5rem 2rem; background: #002b5b; color: #ffffff; }
.content { padding: 2rem; }
.footer { padding: 1.5rem 2rem; background: #f4f4f7; color: #4a4a4a; font-size: 0.85rem; }
a { color: #00c2c7; }
h1, h2, h3 { margin: 0 0 0.75rem; }
ul { margin: 0; padding-left: 1.25rem; }
</style>
</head>
<body>
<div class="container">
<div class="header">
<?php if ( ! empty( $branding['logo'] ) ) : ?>
<p><img src="<?php echo esc_url( $branding['logo'] ); ?>" alt="<?php esc_attr_e( 'Wide Zone Co.', 'widezone-core' ); ?>" style="max-height:48px;" /></p>
<?php endif; ?>
<h1><?php esc_html_e( 'Boundless Thinking. Unified Impact.', 'widezone-core' ); ?></h1>
</div>
<div class="content">
<h2><?php esc_html_e( 'New Job Application', 'widezone-core' ); ?></h2>
<p><?php esc_html_e( 'A candidate has submitted a new application through the careers experience.', 'widezone-core' ); ?></p>
<ul>
<li><strong><?php esc_html_e( 'Role', 'widezone-core' ); ?>:</strong> <?php echo esc_html( $job_title ); ?></li>
<li><strong><?php esc_html_e( 'Name', 'widezone-core' ); ?>:</strong> <?php echo esc_html( $context['name'] ?? '' ); ?></li>
<li><strong><?php esc_html_e( 'Email', 'widezone-core' ); ?>:</strong> <a href="mailto:<?php echo esc_attr( $context['email'] ?? '' ); ?>"><?php echo esc_html( $context['email'] ?? '' ); ?></a></li>
<?php if ( ! empty( $context['cv_url'] ) ) : ?>
<li><strong><?php esc_html_e( 'CV / Portfolio', 'widezone-core' ); ?>:</strong> <a href="<?php echo esc_url( $context['cv_url'] ); ?>"><?php esc_html_e( 'View submission', 'widezone-core' ); ?></a></li>
<?php endif; ?>
</ul>
<?php if ( ! empty( $context['message'] ) ) : ?>
<h3><?php esc_html_e( 'Cover Message', 'widezone-core' ); ?></h3>
<p><?php echo nl2br( esc_html( $context['message'] ) ); ?></p>
<?php endif; ?>
</div>
<div class="footer">
<p><?php echo esc_html( $branding['footer'] ?? __( 'This message was generated by the Wide Zone Core platform.', 'widezone-core' ) ); ?></p>
</div>
</div>
</body>
</html>
